### ISSUE TITLE
:local_base_dir breaks old configurations

### ISSUE THREAD

**Issue by scuben** [rjocoleman/capistrano-upload-config#13]
The new default is set :`local_base_dir, ''`. But that resolves to the root of the filesystem. I could make my deployment working again by setting set `:local_base_dir, '.'`. Wouldn't that be the correct new default setting?

Update: that solved config:check but for a deployment (config:push) I needed to revert to 0.7.0.

**Comment by rjocoleman** [comment]
thanks @scuben you're 100% correct. I will update this, release a new version and yank 0.8.0

**Comment by rjocoleman** [comment]
I have released v0.8.1 which fixes this. Sorry for the oversight! 

Fixed via https://github.com/rjocoleman/capistrano-upload-config/commit/a45579997973528c9aa1347bf338dcbc3616b3e9

**Comment by cibulka** [comment]
`0.8.1` did not fix anything for me, had to downgrade to `0.7.0` where everything works as expected. This is output of my `cap production deploy:check`:

```
 INFO Uploading config ./.env.production as .env
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as XXX@XX.XX.XX.XXX: No such file or directory @ rb_sysopen - /.env.production


Caused by:
Errno::ENOENT: No such file or directory @ rb_sysopen - /.env.production

Tasks: TOP => deploy:check:linked_files => config:push
(See full trace by running task with --trace)

```

**Comment by rjocoleman** [comment]
Hmm, What does your linked file array look like?

**Comment by cibulka** [comment]
Thanks for replying in seconds! :)

I'm using [Capistrano setup](https://github.com/roots/bedrock-capistrano) of [Roots/Bedrock](https://github.com/roots/bedrock) for deployment. This is the line in `deploy.rb` that, I believe, concern this?

```
set :linked_files, fetch(:linked_files, []).push('.env')
```

**Comment by rjocoleman** [comment]
Thanks, that's it! I am just on a layover between flights - I've yanked v0.8.1 too and I'll get something more robust and backwards compatible up when I'm back on the ground properly

**Comment by cibulka** [comment]
Back on the ground? :)

**Comment by rjocoleman** [comment]
This should be fixed in the newly release 0.8.2. 
It's backwards compatible with v7 as it has a default `local_base_dir` of the current directory.

I had introduced some redundant and faulty logic when adding this feature and it's been removed :)
